#print different data types in ansible
- name: print different data types
  hosts: localhost
  vars:
    name: "dileep"
    skills:
    - aws
    - azure
    - rpa
    - ansible
    experience:
      aws: 1
      azure: 2
      rpa: 5
      ansible: 2
    trainer: true
  tasks:
  - name: print key value first
    ansible.builtin.debug:
      msg: "name of the variable {{name}}"

  - name: print list value
    ansible.builtin.debug:
      msg: "list value is {{skills}}"

  - name: print map value
    ansible.builtin.debug:
      msg: "list value is {{experience}}"