# install packages using package module
- name: install package
  hosts: localhost
  become: true
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'ansible', state: 'present'}
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'absent'}